### PR TITLE
Paperboy User Story/ Journey

### PR DESCRIPTION
**Pull request by beacham63**
Good day,
    I hope everyone is well! I have written a draft of the Paperboy  user story/journey. Please feel free to give feedback or make changes as you see fit!

### CODE REVIEW

**Comment by blink1073** [comment]
Hi @beacham63!  Thanks for submitting your first PR to paperboy!

**Comment by beacham63** [comment]
Good morning Steven,
     I renamed the file to .md, but it is not clear based on the guide how
to directly convert my .txt file to .md.

Sincerely,
     Kalen Beacham

**Comment by timkpaine** [comment]
appveyor failure looks unrelated, probably a dependency issue

**Comment by beacham63** [comment]
> Do you mind converting the file to Markdown and renaming to `.md`?

Good afternoon! I believe the user story is now a .md file. I have double-checked on my end to make sure the file was converted.

**Pull request merged**
